plugins {
    id 'com.android.application'
}

android {
    namespace 'com.base44.apk'
    compileSdk 35

    defaultConfig {
        applicationId 'com.base44.apk'
        minSdk 14
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.8.0'
}
