name: Create Android Keystore

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release-key.jks \
            -alias hesab-sarraf \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "TempPass123!" \
            -keypass "TempPass123!" \
            -dname "CN=Hesab Sarraf, OU=Android, O=Hesab Sarraf, L=Unknown, ST=Unknown, C=AF"

      - name: Convert keystore to Base64
        run: |
          base64 -w 0 release-key.jks > keystore_base64.txt

      - name: Upload keystore files
        uses: actions/upload-artifact@v4
        with:
          name: hesab-sarraf-keystore
          path: |
            release-key.jks
            keystore_base64.txt
